'use client';

import Head from 'next/head';
import Link from 'next/link';
import styles from '@/app/home.module.css';
import Image from 'next/image';
import { useEffect, useRef } from 'react';

export default function Home() {
  const aboutRef = useRef(null);
  const contactRef = useRef(null);
  const featuresRef = useRef(null);

  useEffect(() => {
    const handleClick = (event) => {
      if (event.target.classList.contains('navLink') && event.target.href.includes('about')) {
        aboutRef.current.scrollIntoView({ behavior: 'smooth' });
      }
      if (event.target.classList.contains('navLink') && event.target.href.includes('contact')) {
        contactRef.current.scrollIntoView({ behavior: 'smooth' });
      }
      if (event.target.classList.contains('navLink') && event.target.href.includes('features')) {
        featuresRef.current.scrollIntoView({ behavior: 'smooth' });
      }
    };

    document.addEventListener('click', handleClick);

    return () => {
      document.removeEventListener('click', handleClick);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Bail Reckoner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navbar}>
        <ul className={styles.navList}>
          <li className={styles.navItem}>
            <Link legacyBehavior href="/">
              <a className={styles.navLink}>Home</a>
            </Link>
          </li>
          <li className={styles.navItem}>
            <Link legacyBehavior href="/about">
              <a className={styles.navLink}>About</a>
            </Link>
          </li>
          <li className={styles.navItem}>
            <Link legacyBehavior href="/features">
              <a className={styles.navLink}>Features</a>
            </Link>
          </li>
          <li className={styles.navItem}>
            <Link legacyBehavior href="/contact">
              <a className={styles.navLink}>Contact</a>
            </Link>
          </li>
          <li className={styles.navItem}>
            <Link legacyBehavior href="/login">
              <a className={styles.navLink + ' ' + styles.button}>Login</a>
            </Link>
          </li>
          <li className={styles.navItem}>
            <Link legacyBehavior href="/register">
              <a className={styles.navLink + ' ' + styles.button}>Register</a>
            </Link>
          </li>
        </ul>
      </nav>

      <header className={styles.header}>
        <h1 className={styles.title}>Bail Reckoner</h1>
        <p className={styles.description}>Welcome to the Bail Reckoner application.</p>
        <div className={styles.projectDetails}>
          <div>
            <h2 ref={aboutRef} className={styles.sectionHeading}>About</h2>
            <p className={styles.para}>
            Bail Reckoner is a user-friendly web application designed to help individuals estimate their bail amount based on various factors. Our innovative system utilizes advanced algorithms and legal data to provide a personalized bail calculation, giving users a better understanding of their financial obligations. We firmly believe that access to justice should be equitable for all. Bail Reckoner strives to empower individuals by providing transparent and reliable information about the bail process. The app is committed to making the bail process more accessible and understandable for everyone. We aim to ensure that individuals have access to accurate and reliable information so they can navigate the legal system with confidence. Our team is dedicated to continuously improving our system and providing the best possible experience for our users. We encourage you to explore our features and contact us with any questions or feedback you may have. Your input is valuable to us as we strive to create a more just and equitable system for all.
</p>
          </div>
          <Image
            src="/images.jpeg"
            alt="Bail Reckoner Logo"
            width={500}
            height={450}
            quality={100}
            className={styles.image}
          />
        </div>
      </header>

      <main>
        <section ref={featuresRef} className={styles.section + ' ' + styles.features}>
          <h2 className={styles.sectionHeading}>Features</h2>
          <p className={styles.para}>
            Our platform offers a wide range of features to simplify the bail process.Bail Reckoner is a user-friendly web application designed to help individuals estimate their bail amount based on various factors. Our innovative system utilizes advanced algorithms and legal data to provide a personalized bail calculation, giving users a better understanding of their financial obligations. We firmly believe that access to justice should be equitable for all. Bail Reckoner strives to empower individuals by providing transparent and reliable information about the bail process. The app is committed to making the bail process more accessible and understandable for everyone. We aim to ensure that individuals have access to accurate and reliable information so they can navigate the legal system with confidence. Our team is dedicated to continuously improving our system and providing the best possible experience for our users. We encourage you to explore our features and contact us with any questions or feedback you may have. Your input is valuable to us as we strive to create a more just and equitable system for all.
          </p>
          <ul className={styles.featuresList}>
            <li className={styles.featureItem}>
              <i className={styles.featureIcon}></i>
              <h3 className={styles.featureTitle}>Personalized Bail Calculations</h3>
              <p className={styles.featureDescription}>
                Get a tailored bail estimate based on your unique circumstances.
              </p>
            </li>
            <li className={styles.featureItem}>
              <i className={styles.featureIcon}></i>
              <h3 className={styles.featureTitle}>Advanced Algorithms</h3>
              <p className={styles.featureDescription}>
                Our system uses sophisticated algorithms to ensure accurate and reliable results.
              </p>
            </li>
            <li className={styles.featureItem}>
              <i className={styles.featureIcon}></i>
              <h3 className={styles.featureTitle}>Legal Data Integration</h3>
              <p className={styles.featureDescription}>
                We integrate up-to-date legal data to provide the most accurate information.
              </p>
            </li>
          </ul>
        </section>

        <section ref={contactRef} className={styles.section + ' ' + styles.contact}>
          <h2 className={styles.sectionHeading}>Contact</h2>
          <p className={styles.para}>
            Have questions or feedback? Were here to help!
          </p>
          <form className={styles.contactForm}>
            <label htmlFor="name">Name:</label>
            <input type="text" id="name" name="name" className={styles.formInput} />

            <label htmlFor="email">Email:</label>
            <input type="email" id="email" name="email" className={styles.formInput} />

            <label htmlFor="message">Message:</label>
            <textarea id="message" name="message" className={styles.formInput} />

            <button type="submit" className={styles.button}>Send</button>
          </form>
        </section>
      </main>

      <footer className={styles.footer}>
        <p className={styles.copyright}>&copy; 2023 Bail Reckoner. All rights reserved.</p>
      </footer>
    </>
  );
} 